# Generated by Django 4.2 on 2026-04-17 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='conductor',
            field=models.ForeignKey(blank=True, help_text='The person who will conduct/run this meeting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_meetings', to=settings.AUTH_USER_MODEL),
        ),
    ]
