# Generated by Django 4.2 on 2026-06-14 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_activitylog_userteammembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='meetings.team'),
        ),
    ]
